baseurl = "http://key-amb.github.io/App-Koyomi-Doc"
languageCode = "en-us"
title = "Koyomi"
theme = "bootie-docs"
copyright = "Copyright (c) 2015, YASUTAKE Kiyoshi; All rights reserved."

[params]
  description = "A simple distributed job scheduler."
  #withSitePosts = true
  searchDomain = "key-amb.github.io/App-Koyomi-Doc"
  noCategoryLink = true
  repositoryUrl = "https://github.com/key-amb/perl5-App-Koyomi/"
  highlightStyle = "magula"

[[params.mainMenu]]
  name = "About"
  link = "about"

[[params.mainMenu]]
  name = "Quickstart"
  link = "getting-started"

[[params.mainMenu]]
  name = "Index"
  link = "index"
