baseurl = "https://progrhyme.github.io/App-Koyomi-Doc"
languageCode = "en-us"
title = "Koyomi"
theme = "bootie-docs"
copyright = "Copyright (c) 2015-2017, IKEDA Kiyoshi; All rights reserved."

[params]
  description = "A simple distributed job scheduler."
  #withSitePosts = true
  searchDomain = "progrhyme.github.io/App-Koyomi-Doc"
  noCategoryLink = true
  repositoryUrl = "https://github.com/progrhyme/perl5-App-Koyomi/"
  highlightStyle = "magula"

[[menu.main]]
  name   = "About"
  url    = "/about/"
  weight = 20

[[menu.main]]
  name   = "Quickstart"
  url    = "/getting-started/"
  weight = 30
